########### In terminal ###########
cd ~    # move to home directory
   mkdir projects    # make a new directory called projects
cd projects    # move to ~/projects directory
mkdir murders    # make new directory called murders inside of projects
cd murders    # move to ~/projects/murders/
mkdir data rda    # make two new directories, one is data the other is rda folder
ls    # to check if we indeed have one data folder and one rda folder
pwd    # check the current working directory
mkdir figs    # make a directory called figs to store figures

########## In RStudio ########
# pick existing directory as new project
getwd()    # to confirm current working directory
save()    # save into .rda file, .RData is also fine but less preferred
ggsave("figs/barplot.png")    # save a plot generated by ggplot2 to a dir called "figs"

install.packages("caTools")
install.packages("tidyverse")
install.packages("shiny")
install.packages("knitr")
install.packages("esquisse")
install.packages("janitor")
tinytex::tlmgr_update()
tinytex::reinstall_tinytex()
install.packages("tinytex")
update.packages(checkBuilt=TRUE, ask=FALSE)
